name: genmod
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - pip
  - python=3.11
  - setuptools
  - numpy
  - black
  - black-jupyter
  - pylint
  - notebook
  - tqdm
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - pytest
  - pandas
  - ipywidgets
  - pillow
  - opencv
  - scipy
  - matplotlib
  - scikit-learn
